### ISSUE TITLE
Clean out what script tags we are using

### ISSUE THREAD

**Issue by geooot** [tamu-datathon-org/gigabowser#126]
- Remove unnecessary script tags (do we need popper.js and jquery?)
- index.js has two script tags
- make sure necessary CDN loaded scripts use a good CDN with a long cache time
- add `defer` to basically all script tags as no javascript should be necessary to do a "first paint" of the website

**Comment by phulsechinmay** [comment]
@geooot We're using jquery in index.js, should we switch to a non-jquery version?

Also, popper.js is a dependency of tippy.js

**Comment by geooot** [comment]
@phulsechinmay We might also not be able to remove jquery because the bootstrap modal might need it...

**Comment by phulsechinmay** [comment]
@geooot That's true. Might be best to leave it in for now.

Also, other than jquery and bootstrap, we should be able to make all other scripts `defer`?

**Comment by geooot** [comment]
@phulsechinmay I think we should be able to defer all of them but I am not sure. We should definitely try to defer as much as possible
