### ISSUE TITLE
Add section for Summer Bootcamp

### ISSUE THREAD

**Issue by geooot** [tamu-datathon-org/gigabowser#162]
<img width="1541" alt="image" src="https://user-images.githubusercontent.com/7832610/87980188-c8261480-ca98-11ea-8fdf-0a4857d5624f.png">

Notes: 
- It would be nice to add a graphic on top, try to find one
- Make the buttons side by side (and look nice)
- The background should be the same as the one we used a long time ago for the about section

**Comment by geooot** [comment]
Here is the inspect-element changes I made. Note: you should make the correct classes and stuff.
```
<div id="about" class="container">
    <div class="about-content row justify-content-center">
      <div class="col-lg-10 col-md-12 col-sm-12 d-flex flex-column justify-content-center my-5 text-center">
        <div class="container px-0">
          <h1 class="section-title about-title p-0">Summer Bootcamp</h1>
        </div>
        <br>
        <p class="about-header">Get ready for TAMU Datathon with our July 25th Summer Bootcamp</p>
        <p class="about-description">All courses will be free and will prepare you for TAMU Datathon in October. Go to the events page and join our slack to learn more!</p>
        <button class="btn btn-outline-primary btn-lg">Check out the workshops!</button>
        <button class="btn btn-outline-primary btn-lg">Join our Slack!</button>
      </div>
      
    </div>
  </div>
```

**Comment by samarthdave** [comment]
Here's what it looks like so far. I think we can should the two images (this image of TD logo on right with About section image):

![image](https://user-images.githubusercontent.com/4997589/88083100-3fff4800-cb48-11ea-98aa-db8b77e3e947.png)

I can swap these two images and get some better looking buttons.

**Comment by geooot** [comment]
@samarthdave 
I think the buttons are fine. But it would be nice to have a better graphic
