### ISSUE TITLE
Fix Countdown Timer to end on Oct. 1st

### ISSUE THREAD

**Issue by geooot** [tamu-datathon-org/gigabowser#179]

**Comment by phulsechinmay** [comment]
<img width="586" alt="image" src="https://user-images.githubusercontent.com/22554368/92681377-16b29b00-f2f3-11ea-8a4c-33e22026eb47.png">

Showing `21d 39m` on Sept 9th 11:21 pm. That adds up to October 1st 12:00am. I think we good
