### ISSUE TITLE
Change navbar same-page links to javascript-based scrolling

### ISSUE THREAD

**Issue by phulsechinmay** [tamu-datathon-org/gigabowser#19]
**Problem:** Navbar same-page items link to sections on the page, and scroll to the sections on click. However, every click on these items is technically a new URL (with no outgoing request), but still does add onto the browsing history.

**Fix:** Implement Javascript-based scrolling to fix the history problem and have smoother scrolling,

**Comment by geooot** [comment]
Fixed in #62
