### ISSUE TITLE
Meet The Team Section

### ISSUE THREAD

**Issue by phulsechinmay** [tamu-datathon-org/gigabowser#23]
* Create cards for each team member with their name, position & two links.
**Ideas:**
* Basic card with circular profile picture, centered name and position & links on the same line:
![image](https://user-images.githubusercontent.com/22554368/78911381-dac99000-7a4b-11ea-8dcb-0fedc0f36f5b.png)

**Comment by geooot** [comment]
I think we should keep things centered for consistency:
![image](https://user-images.githubusercontent.com/7832610/78912374-22045080-7a4d-11ea-8858-67e7a03ed16c.png)

**Comment by phulsechinmay** [comment]
That looks pretty good, but the cards look pretty plain. Any ideas on improving color on there?

P.S: I don't think we need catchphrases on the cards so I'll drop the last line on there

**Comment by geooot** [comment]
Maybe something like this?
![image](https://user-images.githubusercontent.com/7832610/78914057-84f6e700-7a4f-11ea-8dbb-5f049f2891b2.png)

**Comment by phulsechinmay** [comment]
@geooot It's better but the color doesn't seem distinct enough. Let me try out a few different ideas and we can send them here.

**Comment by geooot** [comment]
@phulsechinmay 
I know this is kinda wacky but check this out:
![image](https://user-images.githubusercontent.com/7832610/79006400-b4285980-7b1e-11ea-979b-1d0acb8ce4e4.png)

**Comment by phulsechinmay** [comment]
Oooh man that looks a bit chaotic. Can you commit to another branch so we can play around with having different images in each card? With different names and images it might look more or less chaotic, we could judge better then.

Also how's this: (we can change the colors if needed)
![image](https://user-images.githubusercontent.com/22554368/79006518-f487d780-7b1e-11ea-94ae-d053be862797.png)

**Comment by geooot** [comment]
I don't really like the colored borders on either. I think its a bit tacky and doesn't fit with the rest.

**Comment by phulsechinmay** [comment]
@geooot Yeah I see that. We could discuss this more in the meeting. Should we ask design for their input? Or we can let them focus on graphics and keep this among dev

**Comment by geooot** [comment]
I think we could give them options and let them weigh in but the final call can just be made internally.
