### ISSUE TITLE
[FAQ Section] Change BG to pastel version and make Q&A more distinct

### ISSUE THREAD

**Issue by geooot** [tamu-datathon-org/gigabowser#48]
![](https://user-images.githubusercontent.com/7832610/79082036-56e00400-7ce8-11ea-8e08-51700541b808.png)

- Change the background of the section to a more pastel green and the text to a more dark color (but not black). See image for reference above but don't take colors too seriously (I personally think it could be a lighter green).
- Make the Questions more distinct than the answers. I think the switch to the pastel colors will already do most of this for you but play around with borders, underlines, colors, or all of the above to make the Qs more distinct.
- Make links have an underline of sorts (for clarity). The links in the screenshot above are a `wavy` underline

In general, this is a pretty open-ended issue, please send many screenshots of possible versions in this issue.

**Comment by samarthdave** [comment]
Here's what it's looking like. I changed the anchors to a more traditional blue. Added variables in the PR at top of ```index.scss``` file. Let me know what you think.

![image](https://user-images.githubusercontent.com/4997589/79590935-75098380-809d-11ea-830e-883f14b2881e.png)

**Comment by geooot** [comment]
@samarthdave I like it!

**Comment by samarthdave** [comment]
I like that idea. I'll try and make a subtle, solid divider.

**Comment by samarthdave** [comment]
Okay I think I should have gone dashed. The solid line doesn't seem to fit in well.

![image](https://user-images.githubusercontent.com/4997589/79594524-c23c2400-80a2-11ea-963a-e735c3238ae5.png)

**Comment by samarthdave** [comment]
Now I think I've got something good. I went to about 30% of available width and made it thicker. What do you think?

![image](https://user-images.githubusercontent.com/4997589/79594928-91102380-80a3-11ea-96ba-9cc785a3c036.png)

**Comment by geooot** [comment]
I think 2px height is better personally.
![image](https://user-images.githubusercontent.com/7832610/79596214-c6b60c00-80a5-11ea-8162-34a2d85b2ba4.png)

And also make sure to correctly add a <hr> between the two columns for mobile view:
![image](https://user-images.githubusercontent.com/7832610/79596257-da617280-80a5-11ea-995c-6cff46f90b9d.png)

**Comment by samarthdave** [comment]
Desktop and mobile are shown below. There's a slight padding difference that you can notice if you look close enough... 🙉 
- dark green color for title (and questions & answers)
- responsive separator for 2 columns
- 2px height

![image](https://user-images.githubusercontent.com/4997589/79623499-4366db80-80e2-11ea-8e72-c6018d8d7db4.png)
![image](https://user-images.githubusercontent.com/4997589/79623533-82952c80-80e2-11ea-8006-2f924fd8f903.png)
