### ISSUE TITLE
Make are Titles more Jazzy

### ISSUE THREAD

**Issue by geooot** [tamu-datathon-org/gigabowser#49]
There is an inconsistency in our Section Titles (in particular with colors). The about section has a colored title that matches the section but the industries section title is black. Plus, the white sections have just a plain black color.

- Change the industries section color to a dark blue
- Change the color of the white section titles to something different than pure black
- Find ways to up our title game (Maybe we could do something with like an offset highlighter look?)
   -  ![image](https://user-images.githubusercontent.com/7832610/79513879-8b1a3400-800a-11ea-8ab0-8481d2694183.png)

Please post screenshots of options on this issue.

**Comment by danielabreo** [comment]
For the industries section, are you sure we want a dark blue and not a pastel blue (which would match FAQ)

**Comment by geooot** [comment]
You mean for the title text @danielabreo

**Comment by danielabreo** [comment]
thoughts?
<img width="863" alt="1" src="https://user-images.githubusercontent.com/34114190/79716697-20345b80-829d-11ea-9d33-a2e37ba39a3c.png">
<img width="901" alt="2" src="https://user-images.githubusercontent.com/34114190/79716699-20ccf200-829d-11ea-91f0-e9c2feb54837.png">
<img width="901" alt="3" src="https://user-images.githubusercontent.com/34114190/79716700-21658880-829d-11ea-9ebc-f6cc52d0b984.png">
<img width="1008" alt="4" src="https://user-images.githubusercontent.com/34114190/79716701-21fe1f00-829d-11ea-88d7-614ecabee77c.png">
<img width="889" alt="5" src="https://user-images.githubusercontent.com/34114190/79716702-21fe1f00-829d-11ea-84e1-a6acea7f0aad.png">
<img width="889" alt="6" src="https://user-images.githubusercontent.com/34114190/79716703-2296b580-829d-11ea-9589-2af632c54836.png">
<img width="901" alt="7" src="https://user-images.githubusercontent.com/34114190/79716704-2296b580-829d-11ea-91a3-a78a47b6243d.png">
<img width="901" alt="8" src="https://user-images.githubusercontent.com/34114190/79716705-232f4c00-829d-11ea-87b6-c2db2651ef2f.png">
<img width="1008" alt="9" src="https://user-images.githubusercontent.com/34114190/79716706-232f4c00-829d-11ea-812a-3cd41fa8e9a7.png">

**Comment by phulsechinmay** [comment]
https://stackoverflow.com/questions/51116847/offset-header-highlight-with-before-and-z-index-css-only/51117409

This might be helpful with the offset highlighter effect

**Comment by geooot** [comment]
Maybe something like this?
![image](https://user-images.githubusercontent.com/7832610/79780901-4213f980-8302-11ea-8489-12d2403f3e12.png)
![image](https://user-images.githubusercontent.com/7832610/79780910-46d8ad80-8302-11ea-8a12-71960872b2b1.png)
![image](https://user-images.githubusercontent.com/7832610/79780919-4b04cb00-8302-11ea-8786-6cfd8195557f.png)

```css
/** each section title has a little bit different css (varying width, and background **/
h1.section-title.sponsor-title::before {
    content: "";
    position: absolute;
    width: 250px;
    background: #19135e0f;
    height: .6em;
    margin-top: 0.5em;
    margin-left: -0.25em;
    z-index: 0;
}
```

**Comment by phulsechinmay** [comment]
![image](https://user-images.githubusercontent.com/22554368/79787254-50ffa980-830c-11ea-8a2b-2deef0b63866.png)

I feel like having more noticeable colors might look good. Maybe have contrasting colors as highlights on sections so they pop out.

**Comment by geooot** [comment]
- Every section should have a colored title that is a darker (and hue shifted) version of the background
- The white sections should have a highlighter effect (like chinmays above) color should be green? Expirement on color
- Colored sections should not have highlighter effect
