### ISSUE TITLE
[Industry Section] Switch out icons with new SVG icons and add all of them, plus more

### ISSUE THREAD

**Issue by geooot** [tamu-datathon-org/gigabowser#52]
- Change icons to the new SVG ones from design
- Increase the vertical height of the section (and thus increase padding between bubbles)
- Add a hover state such that it expands a bit when you hover over it (indicating you can click on it)
    - Take a look at CSS Transitions for help on this
- Add a `cursor:pointer` for the icons so that the user can see the little hand and know that the bubble is clickable 
- Look into adding a tooltip that shows the name of the industry on hover (Reference: https://getbootstrap.com/docs/4.0/components/tooltips/)

**Comment by danielabreo** [comment]
Instead of a tooltip would it make sense to replace the word "Industries" with the name of the industry the user is hovering over? Also, do we still want a tooltip?

**Comment by geooot** [comment]
@danielabreo No don't worry about the tooltip, I tried it and it didn't really work well

**Comment by geooot** [comment]
Closed #65
